package exception;

public class ArithmeticEx {
	


	public static void main(String[] args)   {
		try {
			
			int n=15;
			int m= 0;
			
			
		
		float c= n/m;
		System.out.println("The output is  : " + c);
		
			
		}
		
		catch (Exception e) {
			
			  //e.printStackTrace();
		System.out.println("Exception occurs check the inputvalues");
			 
		}
		
		
		
		
		
		int a = 5;
		int b = 10;
		System.out.println("The value is : " + (a+b));
	}
		
	
	
	
}

	 


